name: CustomList
main: CustomList\Main
version: 1.0.0-ALPHA
api: 3.0.0
author: VMPE Development Team
description: Modified the /list command for PMMP.
commands:
  vmlist:
         description: Allows you to see a list of players online.
    

